%Table list of deffientially expressed genes, generated by DEseq2, is required for uploading
%Three columns of values should be listed in the table in order:
%baseMean, Fold change, adjusted p value

%An example attached can be used to test this script, and the sample data
%should at least include the three coclums of data.

close all
clear
[cvname cvpath] = uigetfile({'*.xlsx';'*.xls';'*.csv';'*.mat'},'File Selector');
da=strcat(cvpath,cvname);
[data, text, alldata] = xlsread(da);

%Gene expression level: baseMean
exp0=data(:,1);

%log10(baseMean)
exp=log10(exp0);

%adjusted p values
signafi=-log10(data(:,3));



baseline=0;
baseline2=0.0;

%USED..........limited fold change=0.75;
limitedFC1=0.75;
limitedFC2=limitedFC1*(-1);

%USED..........limited gene expression level=2;
limitedGeneExp=2;%2.699;%3;%2;%2;%;% 2.8751


a=1;b=1;c=1;d=1;e=1;

data(:,2)=data(:,2)-baseline;



for i=1:length(exp)
    if exp(i)<=limitedGeneExp   %2.4771
        g1(a,1)=data(i,2);
        g2(a,1)=signafi(i);
        g3(a,1)=exp(i);
        a=a+1;
    elseif signafi(i)<1.3010
        gg1(b,1)=data(i,2);
        gg2(b,1)=signafi(i);
        gg3(b,1)=exp(i);
        b=b+1;
    elseif data(i,2)>=limitedFC1
        ggg1(c,1)=data(i,2);
        ggg2(c,1)=signafi(i);
        ggg3(c,1)=exp(i);

        up(c,:)=alldata(i+1,:);
        c=c+1;
    elseif data(i,2)<=limitedFC2
        g2gg1(e,1)=data(i,2);
        g2gg2(e,1)=signafi(i);
        g2gg3(e,1)=exp(i);        

        down(e,:)=alldata(i+1,:);
        e=e+1;
    else
        gggg1(d,1)=data(i,2);
        gggg2(d,1)=signafi(i);
        gggg3(d,1)=exp(i);
        d=d+1;
    end    
end

%sbdata=ggg1;


ov=1.05;
pmax=max(signafi);

if pmax<800
    pmax=pmax;
else
    pmax=max(signafi(find(signafi<800)));
end
lmax=max(data(:,2));
lmin=min(data(:,2));

% limit the fold change to -5~5, but it can be modified
lFC2=5;
g1(g1(:,1)>5,1)=lFC2;
gg1(gg1(:,1)>5,1)=lFC2;
gggg1(gggg1(:,1)>5,1)=lFC2;
ggg1(ggg1(:,1)>5,1)=lFC2;
g2gg1(g2gg1(:,1)>5,1)=lFC2;

g1(g1(:,1)<-5,1)=-lFC2;
gg1(gg1(:,1)<-5,1)=-lFC2;
gggg1(gggg1(:,1)<-5,1)=-lFC2;
ggg1(ggg1(:,1)<-5,1)=-lFC2;
g2gg1(g2gg1(:,1)<-5,1)=-lFC2;





lmin=-(lFC2+0.1);
lmax=lFC2+0.1;

scrsz = get(groot,'ScreenSize');
Vplot=figure('Name','VOCA','NumberTitle','off','Position',[scrsz(3)/10 0 scrsz(3)/1.8 scrsz(4)/1]);
scatter(g1(:,1),g2(:,1),8,'MarkerFaceColor',[0.6 0.6 0.6],'MarkerEdgeColor',[0.6 0.6 0.6])
hold on
scatter(gg1(:,1),gg2(:,1),4,'MarkerFaceColor',[0.2 0.8 1.0],'MarkerEdgeColor',[0.2 0.8 1.0])
hold on
scatter(gggg1(:,1),gggg2(:,1),4,'MarkerFaceColor',[1.0 0.6 1.0],'MarkerEdgeColor',[1.0 0.6 1.0])
hold on
scatter(ggg1(:,1),ggg2(:,1),8,'MarkerFaceColor',[1 0 0],'MarkerEdgeColor',[1 0 0])
hold on
scatter(g2gg1(:,1),g2gg2(:,1),8,'MarkerFaceColor',[0 0 0.8],'MarkerEdgeColor',[0 0 0.8])
axis([lmin*ov lmax*ov -2.5 pmax*ov])


lg1=length(g1(:,1));
lgg1=length(gg1(:,1));
lgggg1=length(gggg1(:,1));
lggg1=length(ggg1(:,1));
lg2gg1=length(g2gg1(:,1));
ylabel('-log10(q value)','FontSize',16,'FontWeight','bold','Color','k');
xlabel('log2(Fold Change)','FontSize',16,'FontWeight','bold','Color','k');
set(gca,'FontSize',16,'FontWeight','bold')
set(gca,'Fontname','times new Roman');
xticks(ceil(lmin*ov):1:floor(lmax*ov))
hold on 
ax=[limitedFC1 limitedFC1];
bx=[limitedFC2 limitedFC2];
ax2=[limitedFC1-baseline2 limitedFC1-baseline2];
bx2=[limitedFC2+baseline2 limitedFC2+baseline2];

ay=[-2.5 pmax*ov];
plot(ax,ay,'--b')
hold on 
plot(bx,ay,'--b')
hold on
cx=[lmin*ov lmax*ov]
cy=[1.3010 1.3010]
plot(cx,cy,'--b')
hold on
plot(ax2,ay,'--k')
hold on 
plot(bx2,ay,'--k')

lgd = legend({['Low expression:' num2str(lg1)],['Not significant:' num2str(lgg1)],['Low fold change:'  num2str(lgggg1)],['Up-regulated:'  num2str(lggg1)],['Down-regulated:'  num2str(lg2gg1)]},'FontSize',16,'TextColor','k','Location','eastoutside')
legend('boxoff')
box on
print(Vplot,'-dpng','-r250','Vplot')




p3max=max(exp);
p3min=min(exp);
if p3min>-2
    p3min=p3min;
else
    p3min=min(exp(find(exp>-2)));
end
%p3max<20 for log10(exp)
if p3max<20
    p3max=p3max;
else
    p3max=max(exp(find(exp<20)));
end



ExpFCplot=figure('Name','VOCA','NumberTitle','off','Position',[scrsz(3)/10 0 scrsz(3)/1.8 scrsz(4)/1]);
scatter(g1(:,1),g3(:,1),8,'MarkerFaceColor',[0.6 0.6 0.6],'MarkerEdgeColor',[0.6 0.6 0.6])
hold on
scatter(gg1(:,1),gg3(:,1),4,'MarkerFaceColor',[0.2 0.8 1.0],'MarkerEdgeColor',[0.2 0.8 1.0])
hold on
scatter(gggg1(:,1),gggg3(:,1),4,'MarkerFaceColor',[1.0 0.6 1.0],'MarkerEdgeColor',[1.0 0.6 1.0])
hold on
scatter(ggg1(:,1),ggg3(:,1),8,'MarkerFaceColor',[1 0 0],'MarkerEdgeColor',[1 0 0])
hold on
scatter(g2gg1(:,1),g2gg3(:,1),8,'MarkerFaceColor',[0 0 0.8],'MarkerEdgeColor',[0 0 0.8])

aay=[limitedGeneExp 100];
plot(ax,aay,'--b')
hold on 
plot(bx,aay,'--b')
hold on
ccx=[-100 100];
ccy=[limitedGeneExp limitedGeneExp]
plot(ccx,ccy,'--b')
hold on

plot(ax2,aay,'--k')
hold on 
plot(bx2,aay,'--k')

axis([lmin*ov lmax*ov p3min*ov p3max*ov])
lgd = legend({['Low expression:' num2str(lg1)],['Not significant:' num2str(lgg1)],['Low fold change:'  num2str(lgggg1)],['Up-regulated:'  num2str(lggg1)],['Down-regulated:'  num2str(lg2gg1)]},'FontSize',16,'TextColor','k','Location','eastoutside')
legend('boxoff')
box on
ylabel('log10(baseMean)','FontSize',16,'FontWeight','bold','Color','k');
xlabel('log2(Fold Change)','FontSize',16,'FontWeight','bold','Color','k');
set(gca,'FontSize',16,'FontWeight','bold')
set(gca,'Fontname','times new Roman');
xticks(ceil(lmin*ov):1:floor(lmax*ov))
print(ExpFCplot,'-dpng','-r250','ExpFCplot')
